version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oc7q5zveihm4"
s3_prefix = "cloud-resume-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []