name: CDK Deploy

on:
  push:
    paths:
      - './cdk/**'
    branches:
      - main
  release:
    types:
      - created
    tags:
      - 'cdk-*'

jobs:
  update-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync website files to S3 (CDK)
        if: contains(github.event.head_commit.message, './cdk/site-contents/')
        run: |
          echo "Syncing website files..."
          aws s3 sync site-contents/ s3://cloud-resume-website-bucket-cdk --delete
        working-directory: ./cdk

      - name: Install dependencies
        run: npm install
        working-directory: ./cdk

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never
        working-directory: ./cdk
